services:
  - type: web
    name: banquetbook
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: banquetbook
          property: connectionString

databases:
  - name: banquetbook
    ipAllowList: []